---
name: Docker

on:
  schedule:
    - cron: '15 14 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2
      - name: "✨ Set matrix output"
        id: set-matrix
        run: |
          MATRIX="$(find * \( -name .zshrc -o -name zshrc.zsh \) -type f -exec dirname {} \;)"
          echo "MATRIX=${MATRIX}" >&2
          echo "::set-output name=matrix::${MATRIX}"

  images:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        env:
          FOLDER: ${{ matrix.file }}"
          TERM: xterm-256color
        run: |
          FOLDER_LOWERCASE="${(L)FOLDER}"
          docker build --build-arg FOLDER="${FOLDER}" --build-arg TERM="${TERM}" -t "zi/${FOLDER_LOWERCASE}"
