---
name: 'Playground'

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed
  push:
    paths:
      - 'profiles/**'
  
jobs:
  play:
    strategy:
      fail-fast: false
      matrix:
        author: [z-shell]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Run: ${{ matrix.author }}'
        run: docker build --build-arg FOLDER="${{ matrix.author }}" --build-arg TERM="${TERM}" -t "zi/${{ matrix.author }}" .
